### ISSUE TITLE
Integrate auto correct when typing in different language 

### ISSUE THREAD

**Issue by dhernandez3098** [synecdozche/dozo-bot#2]
it would be nice if bot can recognize the language you are typing in an help in fixing errors

**Comment by phillanges** [comment]
I like this idea. For a use case I think it'd be best to make this query Google Translate.

I think the flow would be `!tl es como te llamas` 
The first argument is the language in short form. ES for español. 
The rest of it is what you plug into google translate.

**Comment by phillanges** [comment]
Unfortunately the Google API for _did you mean:_ or any corrective guessing is not available. 
I have a hard time seeing how else to implement auto correct for languages. 
Translating a sentence using Google Translate can be done, but I'm not sure if people want that. If they do, then we can open up another issue. 
I'm closing this for now.
